import type { Metadata } from "next";
import { Inter } from "next/font/google";
import React from 'react'
import Header from '../app/components/Header'
import Footer from '../app/components/Footer'
import Main from '../app/components/Main'
import Projects  from "./components/Projects";
import About from '../app/components/About'
import Contact from '../app/components/Contact'
import Resume from '../app/components/Resume'
import Certifications from './components/Certifications';
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "PORTFOLIO Next App",
  description: "Generated by Asmaa",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body>
      <Header /> 
       <Main />
       <Projects />
       <About />
       <Contact />
       <Resume />
       <Certifications />
      <Footer />  

      </body>    
    </html>
  );
}
